import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
  },
  containerBuscar: {
    width: "100%",
    height: 255,
    maxHeight: 255,
    backgroundColor: "white",
    borderColor: "#9e9e9e",
    borderBottomWidth: 1,
    borderTopWidth: 1,
    marginTop: 0,
    alignItems: "center",
    paddingBottom: 5
  },
  containerButtons: {
    marginTop: 0,
    width: "100%",
    height: 50,
    flex: 1,
    flexGrow: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  buttonsTop: {
    backgroundColor: "white",
    height: 40,
    width: 190,
    borderColor: "black",
    borderWidth: 1,
    borderRadius: 3,
    justifyContent: "center",
  },
  textTop: {
    textAlign: "center",
    fontSize: 22,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 70,
  },
  footerButton: {
    backgroundColor: "#1e3a8a",
    flex: 1,
    flexDirection: "row",
    borderLeftWidth: 1,
    borderColor: "white",
    width: "33.33%",
    height: "100%",
    alignItems: "center",
    justifyContent: "space-evenly",
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  footerButtonSair: {
    backgroundColor: "#1e3a8a",
    flex: 1,
    flexDirection: "row",
    borderLeftWidth: 1,
    borderColor: "white",
    width: "33.33%",
    height: "100%",
    alignItems: "center",
    justifyContent: "space-evenly",
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  footerText: {
    color: "white",
    fontSize: 24,
    borderColor: "#ccc",
    textAlign: "center",
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
  footerTextSair: {
    color: "white",
    fontSize: 24,
    borderColor: "#ccc",
    textAlign: "center",
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
  item: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "black",
  },
  containerReceitas: {
    flex: 1,
    flexGrow: 1,
    width: "100%",
    backgroundColor: "white",
    height: 100,
    borderColor: "#9e9e9e",
    borderWidth: 1,
    alignItems: "center",
  },
  indiceReceitas: {
    fontSize: 22,
    textAlign: "center",
    fontWeight: "bold",
  },
  viewReceitas: {
    borderColor: "black",
    borderWidth: 1,
    borderTopWidth: 0,
    width: "90%",
    height: "auto",
    flexGrow: 1,
    marginBottom: 40,
    marginTop: 0,
  },
  btnReceitas: {
    borderTopColor: "black",
    borderTopWidth: 1,
    borderBottomColor: "black",
    borderBottomWidth: 1,
    width: "100%",
    height: 87,
    flexDirection: "row",
    marginBottom: 2,
  },
  nomeReceita: {
    fontSize: 18,
    maxWidth: 260,
    marginLeft: 5,
    marginTop: 2,
  },
  compatReceita: {
    fontSize: 18,
    maxWidth: 260,
    marginTop: "auto",
    marginLeft: "auto",
  }
});

export const stylemodal = StyleSheet.create({
  container: {
    borderColor: "black",
    borderWidth: 1,
  },
  dropdown: {
    marginTop: 0,
    height: 50,
    backgroundColor: "white",
    padding: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    borderColor: "black",
    borderWidth: 1,
    elevation: 2,
  },
  placeholderStyle: {
    fontSize: 18,
  },
  selectedTextStyle: {
    fontSize: 20,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 18,
    borderColor: "black",
  },
  icon: {
    marginRight: 5,
  },
  item: {
    padding: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomColor: "black",
    borderBottomWidth: 1,
  },
  selectedStyle: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 14,
    backgroundColor: "#1e3a8a",
    shadowColor: "#000",
    marginTop: 8,
    marginRight: 5,
    paddingHorizontal: 12,
    paddingVertical: 8,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    borderColor: "black",
    borderWidth: 0.5,
    elevation: 2,
  },
  textSelectedStyle: {
    marginRight: 5,
    fontSize: 20,
    color: "white",
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
});

export default styles;
